# Generated by Django 5.2.6 on 2025-09-19 01:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="名称")),
                ("is_group", models.BooleanField(default=False, verbose_name="是否为群聊")),
                (
                    "create_uid",
                    models.ForeignKey(
                        blank=True,
                        db_column="create_uid",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_create_uid",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="conversations", to=settings.AUTH_USER_MODEL, verbose_name="参与者"
                    ),
                ),
                (
                    "update_uid",
                    models.ForeignKey(
                        blank=True,
                        db_column="update_uid",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_update_uid",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "对话",
                "verbose_name_plural": "对话",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("content", models.TextField(verbose_name="内容")),
                ("timestamp", models.DateTimeField(auto_now_add=True, verbose_name="时间戳")),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="im.conversation",
                        verbose_name="对话",
                    ),
                ),
                (
                    "create_uid",
                    models.ForeignKey(
                        blank=True,
                        db_column="create_uid",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_create_uid",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "read_by",
                    models.ManyToManyField(
                        blank=True, related_name="read_messages", to=settings.AUTH_USER_MODEL, verbose_name="已读用户"
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发送者",
                    ),
                ),
                (
                    "update_uid",
                    models.ForeignKey(
                        blank=True,
                        db_column="update_uid",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_update_uid",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "消息",
                "verbose_name_plural": "消息",
            },
        ),
    ]
